[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  VITE_FIREBASE_API_KEY = "Firebase API Key"
  VITE_FIREBASE_AUTH_DOMAIN = "Firebase Auth Domain"
  VITE_FIREBASE_PROJECT_ID = "Firebase Project ID"
  VITE_FIREBASE_STORAGE_BUCKET = "Firebase Storage Bucket"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "Firebase Messaging Sender ID"
  VITE_FIREBASE_APP_ID = "Firebase App ID"